### ISSUE TITLE
Add support for HACS

### ISSUE THREAD

**Issue by danvy** [pcourbin/ecodevices_rt2#1]
Support for HACS would be nice.
https://github.com/hacs/

**Comment by pcourbin** [comment]
Thanks for the suggestion, I'll work on it! 
I am now just waiting for the validation of my pull requests on "home-assistant/brands" and "home-assistant/wheels-custom-integrations".

**Comment by pcourbin** [comment]
This integration is now available on HACS (since https://github.com/hacs/default/pull/921).
