### ISSUE TITLE
Sensor injoignable si valeur à 0

### ISSUE THREAD

**Issue by otello86** [pcourbin/ecodevices_rt2#107]
Bonjour,
un autre point que je remarque et qui n'est pas très pratique, j'ai l'impression que les sensors sont considérés comme injoignable par HA tant que leur valeur est à 0.
Je m'explique j'ai un compteur d'eau à impulsion branché sur l'entrée 1 du RT2 que je récupère par la config suivante : 
       name: Eau_jour
       type: "post"
       id: 2
       unit_of_measurement: "L"
       state_class: "total_increasing"
       icon: "mdi:water"

Et le sensor correspondant Eau_jour_indexday reste considéré comme injoignable si la valeur est à 0 (notamment de minuit jusqu'à au 1er litre qu'on tire le matin)
Cela peut laisser penser que l'intégration ne fonctionne plus, c'est perturbant.

**Comment by pcourbin** [comment]
Effectivement, c'est un effet de bord d'un autre problème de l'API du EcoRT2.
Parfois, l'API renvoie 0 au lieu de la valeur... ou juste ne répond pas. Du coup, depuis la [v2.2.3](https://github.com/pcourbin/ecodevices_rt2/releases/tag/v2.2.3), j'ai fait une modification pour ne plus considérer les 0 pour les sensors d'index et de prix. Sinon, HA générait des consommations négatives élevées quand un 0 était lu sur un index après une valeur élevée.
Mais donc, un index qui est lui remis à 0 régulièrement par l'EcoRT2 ne sera pas lu tant qu'il n'a pas augmenté...

Je n'ai pas encore trouvé de solution à ça, désolé. Si c'est vraiment bloquant, je pourrais essayer d'y passer un peu plus de temps. Peut être du côté de HA, comme votre solution pour le `customize.yaml` des unités, il y a peut être un moyen pour un sensor spécifique de dire que s'il est injoignable, il faut considérer qu'il vaut 0 ?

**Comment by otello86** [comment]
Pour contourner cela je passe par un appel de ce type qui me renvoie bien les valeurs positives (en cas de consommation sur le réseau) et négatives (en cas de réinjection sur le réseau) :
`
       type: "api"
       component: "sensor"
       api_get: "Get"
       api_get_value: "P"
       api_get_entry: "INSTANT_POSTE1"
`

**Comment by pcourbin** [comment]
Du coup, je tente une nouvelle version [v2.2.6](https://github.com/pcourbin/ecodevices_rt2/releases/tag/v2.2.6) qui propose un paramètre "allow_zero" pour les sensors.
Par défaut, il est à "True", donc les 0 seront biens renvoyés. Si on craint des problèmes sur un sensor, on peut mettre dans le mettre à "False" pour une sensor et les 0 seront alors des "indisponibles".

J'ai aussi corrigé mes ">0" par des "!=0" pour les sensors, vous devriez donc pouvoir utiliser le type `post` au lieu du type `api` pour votre `INSTANT_POSTE1`, vous devriez tout de même avoir les valeurs négatives maintenant.
N'ayant pas de production chez moi, je n'avais pas pensé à ça, merci pour cet exemple ! :-)

**Comment by otello86** [comment]
Je viens de mettre à jour et pour le moment ça tourne bien
