### ISSUE TITLE
Entity state is unavaible

### ISSUE THREAD

**Issue by grichka49** [pcourbin/ecodevices_rt2#7]
## Version of the custom_component
2.2.1
(from HACS)

## Configuration

```yaml
ecodevices_rt2:
  - name: EcoRT2
    host: "192.168.1.105"
    port: 80 # Optional, default: 80
    api_key: "Mypassword"
    update_after_switch: 0.1   # Optional, default: 0 (seconds)
    scan_interval: 30
    devices:
      - name: Index Linky
        type: "api"
        component: "sensor"
        api_get: "Index"
        api_get_value: "All"
        api_get_entry: "Index_TI1"
        device_class: "power"
        unit_of_measurement: "Wh"
        icon: "mdi:flash"

```

## Describe the bug
State of created entites are still "unavaible"
The direct access to the api with http://192.168.1.105/api/xdevices.json?key=Mypassword&Index=all  is OK
In the Integration UI (configuration/ntegration), there is  "2 appareils" (french), "1 entity", each created entity are showned as "appareil" and "entity" (normal ??)
## Debug log

```
Unexpected error fetching ecodevices_rt2 data: Expecting value: line 4 column 19 (char 80)
19:24:01 – (ERREUR) GCE Ecodevices RT2 (intégration personnalisée) - message survenu pour la première fois à 19:17:31 et apparu 15 fois. 

...text
Logger: custom_components.ecodevices_rt2
Source: custom_components/ecodevices_rt2/__init__.py:139
Integration: GCE Ecodevices RT2 (documentation, issues)
First occurred: 19:17:31 (15 occurrences)
Last logged: 19:24:01
Unexpected error fetching ecodevices_rt2 data: Expecting value: line 4 column 19 (char 80)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/ecodevices_rt2/__init__.py", line 139, in async_update_data
    return await hass.async_add_executor_job(ecort2.get_all_cached)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/pyecodevices_rt2/ecodevices_rt2.py", line 84, in get_all_cached
    self.get(complete_command, cached_ms=0)
  File "/usr/local/lib/python3.8/site-packages/pyecodevices_rt2/ecodevices_rt2.py", line 110, in get
    response = self._request(complete_command)
  File "/usr/local/lib/python3.8/site-packages/pyecodevices_rt2/ecodevices_rt2.py", line 62, in _request
    content = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 4 column 19 (char 80)
```

**Comment by pcourbin** [comment]
Hello @grichka49,

Thanks for trying to use this integration!
Unfortunately, up to now, I was only able to test it with my own EcoRT2, thanks to your feedback/tests, I should be able to improve it, thank you :)

**Regarding your error**, the error seems to be generated by the python package [pyecodevices_rt2](https://pypi.org/project/pyecodevices-rt2/) which takes care of the connection with the EcoRT2. 
It seems that your EcoRT2 is returning a malformed JSON. 
_**To check it, please:**_
* Can you copy the returned JSON from the api call to http://192.168.1.105/api/xdevices.json?key=Mypassword&Index=all ?
* Can you tell me the firmware version of your EcoRT2? You can see it by logging into http://192.168.1.105/#!/admin/system 
My own version is **2.01.02** for the software and the firwmare.


**Regarding the second question on "devices"**, you actually have:
* One "device/appareil" for the EcoRT2 (named "EcoRT2" according to your configuration), without any "entity". Yes, it is not necessarily very useful :-)
* One "device/appareil" per element of EcoRT2 that you are going to add, each containing 1 or more "entity".
For example, if you create a "sensor" of type "api", you will have a "device" containing a single "entity".
But if you create an element of type "supplierindex", for example:

``` yaml
- name: Supplier Index 1 (EDF Info)
  type: "supplierindex"
  id: 1
```

then you will have a single "device/appareil" named "Supplier Index 1 (EDF Info)" which will contain 2 entities (sensors, in this case):
- "Supplier Index 1 (EDF Info) Index" which is index 1 of the energy supplier (therefore, exactly what you want to retrieve with your "api" request shown in your issue)
- "Supplier Index 1 (EDF Info) Price" which is the price associated with the index (according to the prices indicated in your EcoRT2), so the value "Price_TI1" of the API call "Price=all".

Please feel free to tell me if anything is unclear.

Oh, et si besoin, nous pouvons échanger en Français ;-)

**Comment by grichka49** [comment]
Bonsoir,
Merci, tu as parfaitement identifié le problème car depuis plus de 3 an j'utilise l'Ecodevice RT et Firefox m'a toujours retourné une erreur de JSON (j'avais mis ça sur le dos de Firefox ...), mais que ce soit ma box précédente Lifedomus ou l'ancienne intégration Ecodevice RT sous HA ça passait sans erreur ... 
J'ai donc mis à jour l'EcoDevice RT dont le fimrware était obsolète et le problème est résolu.
Je te remercie pour ton aide et ton travail sur l'intégration sous Home Assistant ...

**Comment by grichka49** [comment]
It was a malformed JSON issue.  The firmware updating solves the issue (new firmware 2.01.02)
Thanks to  #pcourbin  for his help and his work.

**Comment by pcourbin** [comment]
Parfait, n'hésite pas s'il y a autre chose surtout :-)

**Comment by grichka49** [comment]
Super travail, l'intégration de l'Ecodevice RT sous Lifedomus était une vrai galère, avec ton travail cela devrait être un plaisir ...
